"""empty message

Revision ID: 5f7b8f72d4ef
Revises: 
Create Date: 2019-08-01 14:13:22.489860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7b8f72d4ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('connections_user_id_fkey', 'connections', type_='foreignkey')
    op.drop_constraint('connections_connected_to_fkey', 'connections', type_='foreignkey')
    op.create_foreign_key(None, 'connections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'connections', 'users', ['connected_to'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.create_foreign_key('connections_connected_to_fkey', 'connections', 'users', ['connected_to'], ['id'])
    op.create_foreign_key('connections_user_id_fkey', 'connections', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
