"""empty message

Revision ID: 6cb31a68cc45
Revises: 94b271ad0034
Create Date: 2019-07-26 11:02:14.204020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb31a68cc45'
down_revision = '94b271ad0034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('demoLink', sa.String(length=120), nullable=True))
    op.add_column('projects', sa.Column('githubLink', sa.String(length=120), nullable=True))
    op.add_column('projects', sa.Column('image', sa.String(length=120), nullable=True))
    op.drop_constraint('projects_link_key', 'projects', type_='unique')
    op.create_unique_constraint(None, 'projects', ['image'])
    op.drop_column('projects', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('link', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='unique')
    op.create_unique_constraint('projects_link_key', 'projects', ['link'])
    op.drop_column('projects', 'image')
    op.drop_column('projects', 'githubLink')
    op.drop_column('projects', 'demoLink')
    # ### end Alembic commands ###
