"""empty message

Revision ID: cd908968a646
Revises: 943d877ba987
Create Date: 2019-07-18 00:39:59.257090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd908968a646'
down_revision = '943d877ba987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_skills',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('association_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name='association_table_skill_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='association_table_user_id_fkey')
    )
    op.drop_table('users_skills')
    # ### end Alembic commands ###
